# Generated by Django 3.0.3 on 2020-11-23 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_ok_time_start', models.DateTimeField(blank=True, null=True)),
                ('alert_ok_time_end', models.DateTimeField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('alarm_on', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abay_upper', models.FloatField(null=True)),
                ('abay_lower', models.FloatField(null=True)),
                ('oxbow_deviation', models.FloatField(null=True)),
                ('r4_hi', models.IntegerField(null=True)),
                ('r4_lo', models.IntegerField(null=True)),
                ('r30_hi', models.IntegerField(null=True)),
                ('r30_lo', models.IntegerField(null=True)),
                ('r11_hi', models.IntegerField(null=True)),
                ('r11_lo', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
