# Generated by Django 3.0.3 on 2020-12-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0002_issued_alarms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued_alarms',
            old_name='tigger_time',
            new_name='trigger_time',
        ),
    ]
